math.randomseed(os.time())

local function rand()
    local colors = {}
    for i = 1, 3 do
        table.insert(colors, math.random(0, 255))
    end
    return string.format("#%02x%02x%02x", colors[1], colors[2], colors[3])
end

local groups =
{
    Normal = {fg = rand(), bg = rand()},
    NormalFloat = {fg = rand(), bg = rand()},
    NormalNC = {fg = rand(), bg = rand()},
    
    Delimiter = {fg = rand()},
    Special = {fg = rand()},
    SpecialChar = {fg = rand()},
    SpecialKey = {fg = rand()},
    
    ModeMsg = {fg = rand()},
    MoreMsg = {fg = rand()},
    MsgArea = {fg = rand(), bg = rand()},
    MsgSeparator = {fg = rand()},
    
    Search = {fg = rand(), bg = rand()},
    IncSearch = {fg = rand(), bg = rand()},
    CurSearch = {fg = rand(), bg = rand()},
    QuickFixLine = {fg = rand(), bg = rand()},
    
    Cursor = {fg = rand()},
    TermCursor = {fg = rand()},
    lCursor = {fg = rand()},
    CursorLine = {bg = rand()},
    CursorLineNr = {fg = rand(), bold = true},
    CursorColumn = {bg = rand()},
    CursorIM = {fg = rand(), bg = rand()},
    
    LineNr = {fg = rand()},
    LineNrAbove = {fg = rand()},
    LineNrBelow = {fg = rand()},
    Folded = {fg = rand(), bg = rand()},
    FoldColumn = {fg = rand(), bg = rand()},
    SignColumn = {fg = rand(), bg = rand()},
    
    Function = {fg = rand()},
    Keyword = {fg = rand()},
    Constant = {fg = rand()},
    Identifier = {fg = rand()},
    String = {fg = rand()},
    Type = {fg = rand()},
    Label = {fg = rand()},
    Number = {fg = rand()},
    Float = {fg = rand()},
    Boolean = {fg = rand()},
    Character = {fg = rand()},
    Operator = {fg = rand()},
    PreProc = {fg = rand()},
    Macro = {fg = rand()},
    Statement = {fg = rand()},
    Conditional = {fg = rand()},
    Repeat = {fg = rand()},
    Exception = {fg = rand()},
    Include = {fg = rand()},
    Define = {fg = rand()},
    StorageClass = {fg = rand()},
    Structure = {fg = rand()},
    Typedef = {fg = rand()},
    Tag = {fg = rand()},
    
    Comment = {fg = rand()},
    Todo = {fg = rand(), bg = rand()},
    Note = {fg = rand(), bg = rand()},
    Warning = {fg = rand(), bg = rand()},
    Error = {fg = rand(), bg = rand()},
    
    DiffAdd = {fg = rand(), bg = rand()},
    DiffChange = {fg = rand(), bg = rand()},
    DiffDelete = {fg = rand(), bg = rand()},
    DiffText = {fg = rand(), bg = rand()},
    DiffAdded = {fg = rand()},
    DiffRemoved = {fg = rand()},
    DiffChanged = {fg = rand()},
    DiffFile = {fg = rand()},
    DiffNewFile = {fg = rand()},
    DiffOldFile = {fg = rand()},
    
    GitGutterAdd = {fg = rand()},
    GitGutterChange = {fg = rand()},
    GitGutterDelete = {fg = rand()},
    GitSignsAdd = {fg = rand()},
    GitSignsChange = {fg = rand()},
    GitSignsDelete = {fg = rand()},
    
    TelescopeBorder = {fg = rand()},
    TelescopePromptBorder = {fg = rand()},
    TelescopeResultsBorder = {fg = rand()},
    TelescopePreviewBorder = {fg = rand()},
    TelescopeMatching = {fg = rand()},
    TelescopeSelection = {fg = rand(), bg = rand()},
    TelescopeMultiSelection = {fg = rand()},
    
    NvimTreeFolderName = {fg = rand()},
    NvimTreeFolderIcon = {fg = rand()},
    NvimTreeFileIcon = {fg = rand()},
    NvimTreeExecFile = {fg = rand()},
    NvimTreeOpenedFolderName = {fg = rand()},
    NvimTreeEmptyFolderName = {fg = rand()},
    NvimTreeIndentMarker = {fg = rand()},
    NvimTreeGitDirty = {fg = rand()},
    NvimTreeGitStaged = {fg = rand()},
    NvimTreeGitMerge = {fg = rand()},
    NvimTreeGitRenamed = {fg = rand()},
    NvimTreeGitNew = {fg = rand()},
    NvimTreeGitDeleted = {fg = rand()},
    NvimTreeSpecialFile = {fg = rand()},
    NvimTreeImageFile = {fg = rand()},
    NvimTreeSymlink = {fg = rand()},
    
    StatusLine = {fg = rand(), bg = rand()},
    StatusLineNC = {fg = rand(), bg = rand()},
    StatusLineTerm = {fg = rand(), bg = rand()},
    StatusLineTermNC = {fg = rand(), bg = rand()},
    WinBar = {fg = rand()},
    WinBarNC = {fg = rand()},
    
    TabLine = {fg = rand(), bg = rand()},
    TabLineSel = {fg = rand(), bg = rand()},
    TabLineFill = {fg = rand(), bg = rand()},
    
    Visual = {fg = rand(), bg = rand()},
    VisualNOS = {fg = rand(), bg = rand()},
    
    Directory = {fg = rand()},
    Title = {fg = rand()},
    Question = {fg = rand()},
    WarningMsg = {fg = rand()},
    ErrorMsg = {fg = rand()},
    VertSplit = {fg = rand()},
    ColorColumn = {bg = rand()},
    Conceal = {fg = rand()},
    Ignore = {fg = rand()},
    NonText = {fg = rand()},
    Pmenu = {fg = rand(), bg = rand()},
    PmenuSel = {fg = rand(), bg = rand()},
    PmenuSbar = {bg = rand()},
    PmenuThumb = {bg = rand()},
    SpellBad = {fg = rand(), bg = rand()},
    SpellCap = {fg = rand(), bg = rand()},
    SpellLocal = {fg = rand(), bg = rand()},
    SpellRare = {fg = rand(), bg = rand()},
    MatchParen = {fg = rand(), bg = rand()},
    Whitespace = {fg = rand()},
    EndOfBuffer = {fg = rand()},
    
    DiagnosticError = {fg = rand()},
    DiagnosticWarn = {fg = rand()},
    DiagnosticInfo = {fg = rand()},
    DiagnosticHint = {fg = rand()},
    DiagnosticOk = {fg = rand()},
    DiagnosticUnderlineError = {fg = rand(), undercurl = true},
    DiagnosticUnderlineWarn = {fg = rand(), undercurl = true},
    DiagnosticUnderlineInfo = {fg = rand(), undercurl = true},
    DiagnosticUnderlineHint = {fg = rand(), undercurl = true},
    DiagnosticVirtualTextError = {fg = rand()},
    DiagnosticVirtualTextWarn = {fg = rand()},
    DiagnosticVirtualTextInfo = {fg = rand()},
    DiagnosticVirtualTextHint = {fg = rand()},
    DiagnosticFloatingError = {fg = rand()},
    DiagnosticFloatingWarn = {fg = rand()},
    DiagnosticFloatingInfo = {fg = rand()},
    DiagnosticFloatingHint = {fg = rand()},
    DiagnosticSignError = {fg = rand()},
    DiagnosticSignWarn = {fg = rand()},
    DiagnosticSignInfo = {fg = rand()},
    DiagnosticSignHint = {fg = rand()},
    
    markdownH1 = {fg = rand()},
    markdownH2 = {fg = rand()},
    markdownH3 = {fg = rand()},
    markdownH4 = {fg = rand()},
    markdownH5 = {fg = rand()},
    markdownH6 = {fg = rand()},
    markdownCode = {fg = rand()},
    markdownCodeBlock = {fg = rand()},
    markdownCodeDelimiter = {fg = rand()},
    markdownBlockquote = {fg = rand()},
    markdownListMarker = {fg = rand()},
    markdownOrderedListMarker = {fg = rand()},
    markdownRule = {fg = rand()},
    markdownLinkText = {fg = rand()},
    markdownLinkDelimiter = {fg = rand()},
    markdownLink = {fg = rand()},
    markdownUrl = {fg = rand()},
    markdownId = {fg = rand()},
    markdownIdDeclaration = {fg = rand()},
    markdownBold = {fg = rand(), bold = true},
    markdownItalic = {fg = rand(), italic = true},
    markdownStrike = {fg = rand(), strikethrough = true},
    
    LspReferenceText = {fg = rand()},
    LspReferenceRead = {fg = rand()},
    LspReferenceWrite = {fg = rand()},

    ["@variable"] = {fg = rand()},
    ["@variable.builtin"] = {fg = rand()},
    ["@variable.parameter"] = {fg = rand()},
    ["@variable.member"] = {fg = rand()},
    ["@constant"] = {fg = rand()},
    ["@constant.builtin"] = {fg = rand()},
    ["@constant.macro"] = {fg = rand()},
    ["@module"] = {fg = rand()},
    ["@module.builtin"] = {fg = rand()},
    ["@label"] = {fg = rand()},
    ["@string"] = {fg = rand()},
    ["@string.documentation"] = {fg = rand()},
    ["@string.regexp"] = {fg = rand()},
    ["@string.escape"] = {fg = rand()},
    ["@string.special"] = {fg = rand()},
    ["@character"] = {fg = rand()},
    ["@character.special"] = {fg = rand()},
    ["@number"] = {fg = rand()},
    ["@number.float"] = {fg = rand()},
    ["@boolean"] = {fg = rand()},
    ["@function"] = {fg = rand()},
    ["@function.builtin"] = {fg = rand()},
    ["@function.call"] = {fg = rand()},
    ["@function.macro"] = {fg = rand()},
    ["@function.method"] = {fg = rand()},
    ["@function.method.call"] = {fg = rand()},
    ["@constructor"] = {fg = rand()},
    ["@operator"] = {fg = rand()},
    ["@keyword"] = {fg = rand()},
    ["@keyword.function"] = {fg = rand()},
    ["@keyword.operator"] = {fg = rand()},
    ["@keyword.return"] = {fg = rand()},
    ["@conditional"] = {fg = rand()},
    ["@conditional.ternary"] = {fg = rand()},
    ["@repeat"] = {fg = rand()},
    ["@debug"] = {fg = rand()},
    ["@debug.breakpoint"] = {fg = rand()},
    ["@exception"] = {fg = rand()},
    ["@include"] = {fg = rand()},
    ["@type"] = {fg = rand()},
    ["@type.builtin"] = {fg = rand()},
    ["@type.qualifier"] = {fg = rand()},
    ["@type.definition"] = {fg = rand()},
    ["@attribute"] = {fg = rand()},
    ["@property"] = {fg = rand()},
    ["@field"] = {fg = rand()},
    ["@enum"] = {fg = rand()},
    ["@enum.constant"] = {fg = rand()},
    ["@namespace"] = {fg = rand()},
    ["@symbol"] = {fg = rand()},
    ["@symbol.builtin"] = {fg = rand()},
    ["@punctuation.delimiter"] = {fg = rand()},
    ["@punctuation.bracket"] = {fg = rand()},
    ["@punctuation.special"] = {fg = rand()},
    ["@comment"] = {fg = rand()},
    ["@comment.todo"] = {fg = rand(), bg = rand()},
    ["@comment.note"] = {fg = rand(), bg = rand()},
    ["@comment.warning"] = {fg = rand(), bg = rand()},
    ["@comment.error"] = {fg = rand(), bg = rand()},
    ["@text"] = {fg = rand()},
    ["@text.emphasis"] = {fg = rand()},
    ["@text.strong"] = {fg = rand(), bold = true},
    ["@text.underline"] = {fg = rand(), underline = true},
    ["@text.strike"] = {fg = rand(), strikethrough = true},
    ["@text.title"] = {fg = rand()},
    ["@text.literal"] = {fg = rand()},
    ["@text.uri"] = {fg = rand(), underline = true},
    ["@text.math"] = {fg = rand()},
    ["@text.environment"] = {fg = rand()},
    ["@text.environment.name"] = {fg = rand()},
    ["@text.reference"] = {fg = rand()},
    ["@text.todo"] = {fg = rand(), bg = rand()},
    ["@text.note"] = {fg = rand(), bg = rand()},
    ["@text.warning"] = {fg = rand(), bg = rand()},
    ["@text.danger"] = {fg = rand(), bg = rand()},
    ["@text.diff.add"] = {fg = rand()},
    ["@text.diff.delete"] = {fg = rand()},
    
    ["@lsp.type.class"] = {fg = rand()},
    ["@lsp.type.decorator"] = {fg = rand()},
    ["@lsp.type.enum"] = {fg = rand()},
    ["@lsp.type.enumMember"] = {fg = rand()},
    ["@lsp.type.function"] = {fg = rand()},
    ["@lsp.type.interface"] = {fg = rand()},
    ["@lsp.type.method"] = {fg = rand()},
    ["@lsp.type.namespace"] = {fg = rand()},
    ["@lsp.type.parameter"] = {fg = rand()},
    ["@lsp.type.property"] = {fg = rand()},
    ["@lsp.type.struct"] = {fg = rand()},
    ["@lsp.type.type"] = {fg = rand()},
    ["@lsp.type.typeParameter"] = {fg = rand()},
    ["@lsp.type.variable"] = {fg = rand()},
    
    ["@_parent"] = {fg = rand()},
    ["@attribute.builtin"] = {fg = rand()},
    ["@tag"] = {fg = rand()},
    ["@tag.attribute"] = {fg = rand()},
    ["@tag.delimiter"] = {fg = rand()},
}

return groups
